
package movie_world;

import org.json.simple.JSONArray;


public class Actor_pannel extends javax.swing.JPanel {

    /**
     * Creates new form Actor_pannel
     */
   int actorNO =0;
   JSONArray js = new JSONArray();
    
    public Actor_pannel(int actorno,JSONArray actoArray) {
        actorNO = actorno;
        js = actoArray;
        initComponents();
        favoriteaddBt.setVisible(false);
        delfavoritebt.setVisible(false);
    }
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        nameLb = new javax.swing.JLabel();
        dobLb = new javax.swing.JLabel();
        popularity_progress = new javax.swing.JProgressBar();
        moviesBt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        favoriteaddBt = new javax.swing.JButton();
        delfavoritebt = new javax.swing.JButton();
        photoLb = new javax.swing.JLabel();
        professionLb2 = new javax.swing.JLabel();
        deathLb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bioTf = new javax.swing.JTextArea();

        jButton1.setText("jButton1");

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        setOpaque(false);
        setLayout(null);

        nameLb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameLb.setForeground(new java.awt.Color(252, 196, 25));
        nameLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLb.setText("Actor Name");
        add(nameLb);
        nameLb.setBounds(50, 10, 190, 20);

        dobLb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dobLb.setForeground(new java.awt.Color(252, 196, 25));
        dobLb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dobLb.setText("10-11-2001");
        add(dobLb);
        dobLb.setBounds(0, 110, 100, 20);

        popularity_progress.setBackground(new java.awt.Color(0, 0, 0));
        popularity_progress.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        popularity_progress.setForeground(new java.awt.Color(252, 196, 25));
        popularity_progress.setMaximum(10);
        popularity_progress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        popularity_progress.setStringPainted(true);
        add(popularity_progress);
        popularity_progress.setBounds(0, 240, 290, 20);

        moviesBt.setBackground(new java.awt.Color(0, 0, 0));
        moviesBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-right-arrow-30.png"))); // NOI18N
        moviesBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moviesBtActionPerformed(evt);
            }
        });
        add(moviesBt);
        moviesBt.setBounds(230, 260, 60, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(252, 196, 25));
        jLabel5.setText("POPULAR MOVIES");
        add(jLabel5);
        jLabel5.setBounds(10, 260, 110, 15);

        favoriteaddBt.setBackground(new java.awt.Color(0, 0, 0));
        favoriteaddBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hearts-20 (1).png"))); // NOI18N
        favoriteaddBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favoriteaddBtActionPerformed(evt);
            }
        });
        add(favoriteaddBt);
        favoriteaddBt.setBounds(240, 10, 50, 30);

        delfavoritebt.setBackground(new java.awt.Color(0, 0, 0));
        delfavoritebt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hearts-20.png"))); // NOI18N
        add(delfavoritebt);
        delfavoritebt.setBounds(240, 10, 50, 30);

        photoLb.setBackground(new java.awt.Color(0, 0, 0));
        photoLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/broken_img.png"))); // NOI18N
        add(photoLb);
        photoLb.setBounds(90, 30, 120, 90);

        professionLb2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        professionLb2.setForeground(new java.awt.Color(252, 196, 25));
        professionLb2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        professionLb2.setText("Acting");
        add(professionLb2);
        professionLb2.setBounds(100, 130, 90, 20);

        deathLb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deathLb.setForeground(new java.awt.Color(252, 196, 25));
        deathLb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        deathLb.setText("100000");
        add(deathLb);
        deathLb.setBounds(210, 110, 80, 20);

        bioTf.setBackground(new java.awt.Color(0, 0, 0));
        bioTf.setColumns(20);
        bioTf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bioTf.setForeground(new java.awt.Color(252, 196, 25));
        bioTf.setRows(5);
        bioTf.setText("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb");
        bioTf.setDisabledTextColor(new java.awt.Color(252, 196, 25));
        bioTf.setEnabled(false);
        jScrollPane1.setViewportView(bioTf);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 150, 290, 90);
    }// </editor-fold>//GEN-END:initComponents

    private void moviesBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moviesBtActionPerformed

    }//GEN-LAST:event_moviesBtActionPerformed

    private void favoriteaddBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favoriteaddBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_favoriteaddBtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea bioTf;
    public javax.swing.JLabel deathLb;
    private javax.swing.JButton delfavoritebt;
    public javax.swing.JLabel dobLb;
    public javax.swing.JButton favoriteaddBt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton moviesBt;
    public javax.swing.JLabel nameLb;
    public javax.swing.JLabel photoLb;
    public javax.swing.JProgressBar popularity_progress;
    public javax.swing.JLabel professionLb2;
    // End of variables declaration//GEN-END:variables
}
