/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package movie_world;

/**
 *
 * @author DELL
 */
public class company_pannel extends javax.swing.JPanel {

    /**
     * Creates new form company_pannel
     */
    public company_pannel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name_lb = new javax.swing.JLabel();
        photoLb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        setLayout(null);

        name_lb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name_lb.setForeground(new java.awt.Color(252, 196, 25));
        name_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_lb.setText("name");
        add(name_lb);
        name_lb.setBounds(0, 230, 300, 20);

        photoLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photoLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/broken_img.png"))); // NOI18N
        add(photoLb);
        photoLb.setBounds(20, 40, 260, 170);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel name_lb;
    public javax.swing.JLabel photoLb;
    // End of variables declaration//GEN-END:variables
}
