/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package movie_world;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Image;
import java.io.File;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class profile_pannel extends javax.swing.JPanel {

    String username = "";
    String email = "";
    String mobile = "";
    String address = "";
    String photo = "";

    /**
     * Creates new form profile_pannel
     */
    public profile_pannel(String emailid) {
        initComponents();
        fetchData(emailid);
        jScrollPane2.setVisible(false);
       privacyPannel.setVisible(false);
        FavAcBt.setVisible(false);
        setSize(550, 550);

    }

    public void fetchData(String email) {
        try {
            HttpResponse<String> res = Unirest.get("http://localhost:8000/userdetails").queryString("email", email).asString();
            if (res.getStatus() == 200) {
                String back = res.getBody();
                StringTokenizer st = new StringTokenizer(back, "~");
                int size = st.countTokens();
                System.out.println(size);
                for (int i = 0; i < size; i++) {
                    if (i == 0) {
                        username = st.nextToken();
                    }
                    if (i == 1) {
                        this.email = st.nextToken();
                    }
                    if (i == 2) {
                        mobile = st.nextToken();
                    }
                    if (i == 3) {
                        address = st.nextToken();
                    }
                    if (i == 4) {
                        photo = st.nextToken();
                    }
                }
                nameLb.setText(username.toUpperCase());
                phonenoLb.setText(mobile);
                String [] n =address.split("(?<=\\G.{" + 27 + "})");
                address="";
                    for (String string : n) {
                        address+=string+" "+"\n"+" ";
                    }
                addressTa.setText(address);
                //photoBt.setText(photo);
                emaillb.setText(email);

                ImageIcon ic = new ImageIcon("src/pictures/" + photo);
                Image img = ic.getImage().getScaledInstance(photoBt.getWidth(), photoBt.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon ic1 = new ImageIcon(img);

                photoBt.setIcon(ic1);

               
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nameLb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        emaillb = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        changeEmailBt = new javax.swing.JButton();
        changenumberBt = new javax.swing.JButton();
        changeusernameBt = new javax.swing.JButton();
        logoutBt = new javax.swing.JButton();
        photoBt = new javax.swing.JButton();
        phonenoLb = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        changeAddressBt1 = new javax.swing.JButton();
        backBt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        favMovBt = new javax.swing.JButton();
        FavAcBt = new javax.swing.JButton();
        FavshowBt = new javax.swing.JButton();
        FavoritesBt = new javax.swing.JToggleButton();
        privacyPannel = new javax.swing.JPanel();
        changePasswordBt = new javax.swing.JButton();
        deleteAccBt = new javax.swing.JButton();
        privacyBt = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTa = new javax.swing.JTextArea();

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/username.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(220, 30, 50, 30);

        nameLb.setBackground(new java.awt.Color(0, 0, 0));
        nameLb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameLb.setForeground(new java.awt.Color(252, 196, 25));
        nameLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLb.setText("mmmmmmmmm");
        add(nameLb);
        nameLb.setBounds(270, 40, 230, 20);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/email.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(220, 80, 50, 30);

        emaillb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emaillb.setForeground(new java.awt.Color(252, 196, 25));
        emaillb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emaillb.setText("abc@gmail.com");
        add(emaillb);
        emaillb.setBounds(280, 80, 220, 20);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-home-address-30.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(200, 180, 80, 30);

        changeEmailBt.setBackground(new java.awt.Color(0, 0, 0));
        changeEmailBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-pencil-30.png"))); // NOI18N
        changeEmailBt.setBorder(null);
        changeEmailBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeEmailBtActionPerformed(evt);
            }
        });
        add(changeEmailBt);
        changeEmailBt.setBounds(510, 80, 60, 30);

        changenumberBt.setBackground(new java.awt.Color(0, 0, 0));
        changenumberBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-pencil-30.png"))); // NOI18N
        changenumberBt.setBorder(null);
        changenumberBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changenumberBtActionPerformed(evt);
            }
        });
        add(changenumberBt);
        changenumberBt.setBounds(510, 120, 60, 30);

        changeusernameBt.setBackground(new java.awt.Color(0, 0, 0));
        changeusernameBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-pencil-30.png"))); // NOI18N
        changeusernameBt.setBorder(null);
        changeusernameBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeusernameBtActionPerformed(evt);
            }
        });
        add(changeusernameBt);
        changeusernameBt.setBounds(510, 30, 60, 30);

        logoutBt.setBackground(new java.awt.Color(252, 196, 25));
        logoutBt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logoutBt.setText("LOGOUT");
        logoutBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtActionPerformed(evt);
            }
        });
        add(logoutBt);
        logoutBt.setBounds(170, 400, 140, 22);

        photoBt.setBackground(new java.awt.Color(0, 0, 0));
        photoBt.setText("photo");
        photoBt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 4, true));
        photoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoBtActionPerformed(evt);
            }
        });
        add(photoBt);
        photoBt.setBounds(70, 40, 130, 130);

        phonenoLb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phonenoLb.setForeground(new java.awt.Color(252, 196, 25));
        phonenoLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phonenoLb.setText("62155154464464");
        add(phonenoLb);
        phonenoLb.setBounds(280, 130, 220, 20);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/phone.png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(190, 130, 100, 30);

        changeAddressBt1.setBackground(new java.awt.Color(0, 0, 0));
        changeAddressBt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-pencil-30.png"))); // NOI18N
        changeAddressBt1.setBorder(null);
        changeAddressBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeAddressBt1ActionPerformed(evt);
            }
        });
        add(changeAddressBt1);
        changeAddressBt1.setBounds(510, 190, 60, 30);

        backBt.setBackground(new java.awt.Color(0, 0, 0));
        backBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/backbt (2).png"))); // NOI18N
        backBt.setText("<-");
        backBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtActionPerformed(evt);
            }
        });
        add(backBt);
        backBt.setBounds(10, 10, 50, 37);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jPanel1.setLayout(null);

        favMovBt.setBackground(new java.awt.Color(0, 0, 0));
        favMovBt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        favMovBt.setForeground(new java.awt.Color(252, 196, 25));
        favMovBt.setText("MOVIES");
        favMovBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favMovBtActionPerformed(evt);
            }
        });
        jPanel1.add(favMovBt);
        favMovBt.setBounds(20, 0, 100, 22);

        FavAcBt.setBackground(new java.awt.Color(0, 0, 0));
        FavAcBt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FavAcBt.setForeground(new java.awt.Color(252, 196, 25));
        FavAcBt.setText("ACTOR");
        FavAcBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavAcBtActionPerformed(evt);
            }
        });
        jPanel1.add(FavAcBt);
        FavAcBt.setBounds(20, 80, 100, 20);

        FavshowBt.setBackground(new java.awt.Color(0, 0, 0));
        FavshowBt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FavshowBt.setForeground(new java.awt.Color(252, 196, 25));
        FavshowBt.setText("TV SHOWS");
        FavshowBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavshowBtActionPerformed(evt);
            }
        });
        jPanel1.add(FavshowBt);
        FavshowBt.setBounds(20, 40, 100, 22);

        jScrollPane2.setViewportView(jPanel1);

        add(jScrollPane2);
        jScrollPane2.setBounds(320, 280, 140, 70);

        FavoritesBt.setBackground(new java.awt.Color(0, 0, 0));
        FavoritesBt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FavoritesBt.setForeground(new java.awt.Color(252, 196, 25));
        FavoritesBt.setText("WISHLIST");
        FavoritesBt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FavoritesBtItemStateChanged(evt);
            }
        });
        FavoritesBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavoritesBtActionPerformed(evt);
            }
        });
        add(FavoritesBt);
        FavoritesBt.setBounds(320, 260, 140, 22);

        privacyPannel.setBackground(new java.awt.Color(0, 0, 0));
        privacyPannel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        privacyPannel.setLayout(null);

        changePasswordBt.setBackground(new java.awt.Color(0, 0, 0));
        changePasswordBt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        changePasswordBt.setForeground(new java.awt.Color(252, 196, 25));
        changePasswordBt.setText("CHANGE PASSWORD");
        changePasswordBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordBtActionPerformed(evt);
            }
        });
        privacyPannel.add(changePasswordBt);
        changePasswordBt.setBounds(0, 10, 190, 22);

        deleteAccBt.setBackground(new java.awt.Color(0, 0, 0));
        deleteAccBt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteAccBt.setForeground(new java.awt.Color(252, 196, 25));
        deleteAccBt.setText("DELETE ACCOUNT");
        deleteAccBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccBtActionPerformed(evt);
            }
        });
        privacyPannel.add(deleteAccBt);
        deleteAccBt.setBounds(0, 50, 190, 22);

        add(privacyPannel);
        privacyPannel.setBounds(20, 260, 190, 100);

        privacyBt.setBackground(new java.awt.Color(0, 0, 0));
        privacyBt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        privacyBt.setForeground(new java.awt.Color(252, 196, 25));
        privacyBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-privacy-30.png"))); // NOI18N
        privacyBt.setText("PRIVACY");
        privacyBt.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                privacyBtStateChanged(evt);
            }
        });
        privacyBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privacyBtActionPerformed(evt);
            }
        });
        add(privacyBt);
        privacyBt.setBounds(20, 220, 190, 37);

        addressTa.setBackground(new java.awt.Color(0, 0, 0));
        addressTa.setColumns(20);
        addressTa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addressTa.setForeground(new java.awt.Color(255, 196, 25));
        addressTa.setRows(5);
        jScrollPane1.setViewportView(addressTa);

        add(jScrollPane1);
        jScrollPane1.setBounds(290, 170, 210, 81);
    }// </editor-fold>//GEN-END:initComponents

    private void changeEmailBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeEmailBtActionPerformed
        // TODO add your handling code here:
        new changeFrame("email");
    }//GEN-LAST:event_changeEmailBtActionPerformed

    private void FavAcBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavAcBtActionPerformed
        // TODO add your handling code here:
        new FavoriteForm("actor");

    }//GEN-LAST:event_FavAcBtActionPerformed

    private void changeusernameBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeusernameBtActionPerformed
        // TODO add your handling code here:
        new changeFrame("username").applyBt.addActionListener((e) -> {
            fetchData(dump.email);

        });
    }//GEN-LAST:event_changeusernameBtActionPerformed

    private void logoutBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtActionPerformed
        // TODO add your handling code here:
        File f = new File("src/dump");
        f.delete();
        JOptionPane.showMessageDialog(this, username + " " + "Thanks for Using");
        dump.email = "";
        dump.user = "";
        dump.render = true;
        new newMovieWorld();
    }//GEN-LAST:event_logoutBtActionPerformed

    private void favMovBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favMovBtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_favMovBtActionPerformed

    private void changePasswordBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordBtActionPerformed
        // TODO add your handling code here:
        new changeFrame("password");
    }//GEN-LAST:event_changePasswordBtActionPerformed

    private void FavshowBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavshowBtActionPerformed
        // TODO add your handling code here:
//        new FavoriteForm("tv");
    }//GEN-LAST:event_FavshowBtActionPerformed

    private void deleteAccBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccBtActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "All data related to account will be deleted and will not be recovered", "Delete account", JOptionPane.OK_CANCEL_OPTION);

        if (input == 0) {
            try {
                HttpResponse<String> str = Unirest.get("http://localhost:8000/deleteaccount").queryString("email", dump.email).asString();
                if (str.getStatus() == 200) {
                    File f = new File("src/dump");
                    f.delete();
                    JOptionPane.showMessageDialog(this, username + " " + "Thanks for Using");
                    dump.email = "";
                    dump.user = "";
                    JOptionPane.showMessageDialog(this, "Deleted sucess");
                    new newMovieWorld();

                }
            } catch (Exception ex) {

            }
        }

    }//GEN-LAST:event_deleteAccBtActionPerformed

    private void changeAddressBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeAddressBt1ActionPerformed
        // TODO add your handling code here:
        new changeFrame("address");
    }//GEN-LAST:event_changeAddressBt1ActionPerformed

    private void backBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtActionPerformed
        // TODO add your handling code here:
        new Welcome();

    }//GEN-LAST:event_backBtActionPerformed

    private void photoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoBtActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        jfc.showOpenDialog(null);
        File f = jfc.getSelectedFile();
        String path = f.getPath();
        System.out.println(path);
        ImageIcon ic = new ImageIcon(path);
        Image img = ic.getImage().getScaledInstance(photoBt.getWidth(), photoBt.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic1 = new ImageIcon(img);

        photoBt.setIcon(ic1);

        try {
            HttpResponse<String> res = Unirest.post("http://localhost:8000/changephoto").queryString("email", email).field("photo", new File(path)).asString();
            if (res.getStatus() == 200) {
                String back = res.getBody();
                if (back.contains("sucess")) {
                    JOptionPane.showMessageDialog(this, "Profile Photo changed sucess");

                } else if (back.contains("unsucess")) {
                    JOptionPane.showMessageDialog(this, "Enter details properly");

                }

            } else {
                JOptionPane.showMessageDialog(this, "Error");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_photoBtActionPerformed

    private void FavoritesBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavoritesBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FavoritesBtActionPerformed

    private void FavoritesBtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FavoritesBtItemStateChanged
        // TODO add your handling code here:
        if (FavoritesBt.isSelected()) {
            jScrollPane2.setVisible(true);
        } else {
            jScrollPane2.setVisible(false);
        }
    }//GEN-LAST:event_FavoritesBtItemStateChanged

    private void changenumberBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changenumberBtActionPerformed
        // TODO add your handling code here:
        new changeFrame("phone");
    }//GEN-LAST:event_changenumberBtActionPerformed

    private void privacyBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privacyBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_privacyBtActionPerformed

    private void privacyBtStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_privacyBtStateChanged
        // TODO add your handling code here:
        if(privacyBt.isSelected()){
            privacyPannel.setVisible(true);
        }
        else{
            privacyPannel.setVisible(false);
        }
    }//GEN-LAST:event_privacyBtStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton FavAcBt;
    private javax.swing.JToggleButton FavoritesBt;
    public javax.swing.JButton FavshowBt;
    private javax.swing.JTextArea addressTa;
    public javax.swing.JButton backBt;
    public javax.swing.JButton changeAddressBt1;
    public javax.swing.JButton changeEmailBt;
    public javax.swing.JButton changePasswordBt;
    javax.swing.JButton changenumberBt;
    public javax.swing.JButton changeusernameBt;
    public javax.swing.JButton deleteAccBt;
    private javax.swing.JLabel emaillb;
    public javax.swing.JButton favMovBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JButton logoutBt;
    private javax.swing.JLabel nameLb;
    private javax.swing.JLabel phonenoLb;
    private javax.swing.JButton photoBt;
    private javax.swing.JToggleButton privacyBt;
    private javax.swing.JPanel privacyPannel;
    // End of variables declaration//GEN-END:variables
}
